// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import * as dotenv from 'dotenv';
import { defineConfig } from "prisma/config";

// Erzwingt das Laden der .env Datei aus dem Root-Verzeichnis
dotenv.config();

if (!process.env.DATABASE_URL) {
  throw new Error("DATABASE_URL ist nicht in der .env definiert!");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  datasource: {
    url: process.env.DATABASE_URL,
  },
});